### PR TITLE
NEW Allow overriding of host, port and protocol for URL building

### LINKED ISSUE #149: Add security config to disable destination check
At the moment [the destination check](https://github.com/onelogin/php-saml/blob/570a5d9cc42a1a205355b9212bd182fbe35404d9/lib/Saml2/Response.php#L169-L181) for SAML responses is forced on and can't be disabled.

This can prove problematic because the utility function(s) used to determine the current URL can be wrong (for example, if we have a `X-Forwarded-Port` header that we don't want to use as the actual port).

As there's no way to provide current URL resolution hints it'd be helpful to either define the current environments domain/host/port/etc in some hard-coded way or to disable this destination check entirely.

I've mainly experienced this issue around ports being appended to the host unexpectedly and this has caused errors as there's a mis-match detected by the server that doesn't occur in the real/actual URLs.

### PR DESCRIPTION
**Pull request by dhensby**
Fixes #149 
- Added ability to set custom host/port/protocol
- Added X-Forwarded-Host support
- Updated test coverage to include testing HTTP_X_FORWARDED_PORT
- Split port detection into its own method

### CODE REVIEW

**Comment by pitbulk** [comment]
I thought that you wanted to let the developer to decide if enable or not the use of HTTP_X_FORWARDED_PORT / HTTP_X_FORWARDED_PROTO or not
```
OneLogin_Saml2_Utils::setRequestProto();
OneLogin_Saml2_Utils::setRequestPort();
```

but here you also let the developer to control the host, and this should have impact on security.

**Comment by dhensby** [comment]
This does allow this implicitly.

For example, if I don't want to use the `X-Forwarded-Port` header I can now use `OneLogin_Saml2_Utils::setRequestProto($_SERVER["SERVER_PORT"]);`

Because the `getSelfHost()` method includes a port, one has to be able to override this, so I added this ability. If someone communicates via a proxy to `http://internal.machine.example.com:8080/saml/` and we want to present that as `https://publicsite.com/saml` then these utilities are required

**Comment by pitbulk** [comment]
But if you are able to manipulate the host, then you can bypass the URL validations.
I dislike that part.

I prefer something like adding this attribute
```
     * @var boolean
     */
    private static $_proxyVars = false;
```


```
    public static function getSelfURLhost()
    {
        $currenthost = self::getSelfHost();
        $port = '';
        if (self::isHTTPS()) {
            $protocol = 'https';
        } else {
            $protocol = 'http';
        }
        if (self::$_proxyVars && isset($_SERVER["HTTP_X_FORWARDED_PORT"])) {
            $portnumber = $_SERVER["HTTP_X_FORWARDED_PORT"];
        } else if (isset($_SERVER["SERVER_PORT"])) {
            $portnumber = $_SERVER["SERVER_PORT"];
        }
        if (isset($portnumber) && ($portnumber != '80') && ($portnumber != '443')) {
            $port = ':' . $portnumber;
        }
        return $protocol."://" . $currenthost . $port;
    }



    public static function isHTTPS()
    {
        $isHttps =  (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
                    || (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443)
                    || (self::$_proxyVars && isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https');
        return $isHttps;
    }
```

so you can 
```
OneLogin_Saml2_Utils::enableProxyVars(true);
```
having similar control.

**Comment by dhensby** [comment]
That solution provides much less control because you then have to rely on either a header that can be spoofed (surely this is much more of an issue than allowing a developer to present their site **internally to the app** as one thing but running as another.

Have you tried running this module on a high availability infrastructure so you can understand the issues involved here? You can have servers that legitimately accept requests on one domain/port/protocol but are served by application servers running on another domain/port/protocol.

At the moment some of this is dealt with but it's not opt-in and is forced on, which exposes applications to easily spoofed headers if they aren't behind a proxy AND then doesn't provide a complete solution for those who are.

This resolves both issues in a backwards-compatible way. Although devs who aren't behind a proxy need to take manual intervention (ie: they need to set the port/protocol to make sure it's not spoofed) those relying on this behaviour won't have to do anything. Those that it doesn't work for either way can now get it working.

**Comment by dhensby** [comment]
Just to add a few more thoughts to this PR.

At the moment the general recommendation seems to be "if the port/host/protcol detection is wrong then edit the `$_SERVER` superglobals to what you need". IMO this is very bad practice (to edit superglobals). What this change does is gives exactly the same control to the developer as editing the superglobals but with a properly supported API and without having to change global state that shouldn't be edited.

There is no real difference between a developer doing these two things:

```php
$_SERVER['HTTP_HOST' = 'example.com';

// or

OneLogin_Saml2_Utils::setSelfHost('example.com');
```

The former is (at least) casually recommended in tickets; the latter just provides a formal supported way to do it.

These functions also aid testing without having to edit superglobals too.

**Comment by patkar** [comment]
>  Although devs who aren't behind a proxy need to take manual intervention (ie: they need to set the port/protocol to make sure it's not spoofed)

Sounds like a BC break tough. 

Although #158 with a boolean control flag is already merged, there should the a `setTrustedProxies()` method, which controls from which servers the `X-Forwared-*` headers a trusted, like in Symfony HttpFoundation Request.

```php
// only trust proxy headers coming from this IP addresses
OneLogin_Saml2_Utils::setTrustedProxies(array('192.0.0.1', '10.0.0.0/8'));
```

**Comment by dhensby** [comment]
> Sounds like a BC break tough.

*this* PR is not BC breaking because it keeps all the current behaviour (as of now) and allows an extra opt-in feature. You correctly identify #158 as "breaking" (there's a change in default behaviour that if some relied upon will now need to enable) and that's been merged already.

> Although #158 with a boolean control flag is already merged, there should the a setTrustedProxies() method, which controls from which servers the X-Forwared-* headers a trusted, like in Symfony HttpFoundation Request.

That is unrelated to this PR as this change doesn't deal with trusting headers or not. Perhaps more relevant to be put against the other PR?

---

I'd like to re-iterate that I'm trying to work within the defined patterns and API of what currently exists - I'm not trying to re-architect a solution from the ground up. If we start talking about using Symfony-like approaches then we might as well just include the Symfony http foundation instead of duplicating their code, increasing maintenance burden and the possibilities of regressions.

**Comment by dhensby** [comment]
@pitbulk I'm just running through my open PRs - do you reckon there'll be any movement on this?

**Comment by pitbulk** [comment]
Yes, I plan to do a new release with some security improvements I did (not published yet) and then I will merge that and maybe implement a way to let the developer to provide vy config a baseurlpath (that can set those new parameters )

**Pull request closed without merging**
