### PR TITLE
Support multiple nameid formats

### PR DESCRIPTION
**Pull request by ChinmayPatel**

### CODE REVIEW

**Comment by pitbulk** [comment]
The NameIDFormat value is the one used in order to build the [samlp:NameIDPolicy] of the (http://www.datypic.com/sc/saml2/e-samlp_AuthnRequest.html) and you can see its value is 0 or 1.
and as you saw, also used as SP metadata.

what is the advantage of support multiple NameIDFormat on SP metadata?

**Comment by ChinmayPatel** [comment]
That's fair. One of our clients requested to provide two values. Your link will allow me to go back and request our clients to follow the standards correctly.

**Comment by pitbulk** [comment]
If the IdP want to decide what to send, then there are 2 options:
- Send the unespecified.
- Send no NameIDPolicy.

**Comment by ChinmayPatel** [comment]
Ahh... that makes sense. Definitely helps. Thanks @pitbulk.

**Pull request closed without merging**
