### PR TITLE
Improve Key Rollover management

### PR DESCRIPTION
**Pull request by pitbulk**
- [x] [Be able to register future SP x509cert on the settings and publish it on SP metadata](https://github.com/onelogin/php-saml/commit/aee91b845047b48afb233b603d5587ca3f37d10c)
- [x] [Be able to register more than 1 Identity Provider x509cert, linked with an specific use (signing or encryption)](https://github.com/onelogin/php-saml/pull/206/commits/84aa522b27a8d44cfc2f0229aa8963b9de438eec)
- [x] [Support the ability to parse IdP XML metadata (remote url or file) and be able to inject the data obtained on the settings.](https://github.com/onelogin/php-saml/pull/206/commits/ef78f642aeec8e8b297fd200f3ba9d14ddb03660)

### CODE REVIEW

**Comment by madmatt** [comment]
Hey @pitbulk, this looks great. I've read through the documentation (but not the code) and it looks like it will fulfil the use-case of Azure signing key rollover nicely (ref #140).

So I take it the expectation is that we define the `['x509certMulti']['signing']` array with all the public keys that [Azure provides us in their metadata](https://login.microsoftonline.com/common/FederationMetadata/2007-06/FederationMetadata.xml) - the three listed under `<IDPSSODescriptor>`, and the module will try each in succession?

This is awesome, thanks for implementing!

**Comment by pitbulk** [comment]
Yes, 'x509certMulti' allows to register more than 1 IdP public certificate and define if gonna be used for signing or encryption. The idp metadata parser is able to retrieve all the certificate data.

**Comment by saahilpingle24** [comment]
@pitbulk do you have a timeline in mind for merging this into master?

**Comment by pitbulk** [comment]
If I receive no negative feedback in the following days I will execute a new release next week.

**Pull request merged**
