### PR TITLE
Added 'delete session' callback option

### PR DESCRIPTION
**Pull request by samlev**
Added the option for sending a callback to destroy the session.

### CODE REVIEW

**Comment by samlev** [comment]
Squashed to two commits.

**Comment by pitbulk** [comment]
Can someone review that this is working on Lavarel framework?

@samlev Can you update the Readme with this info?

**Comment by samlev** [comment]
The readme was updated with how to use the callbacks, and I bumped the version number up

The laravel-saml2 library can't be updated until this has been merged (but I have a merge request waiting to go there, too)

I've tested locally with one of my projects (editing the files in the 'vendor' folder), and this works.

**Comment by pitbulk** [comment]
Merged, please let me know if you experience any issue with the lavarel framework.

**Comment by pitbulk** [comment]
I created a new version with this change included:
[php-saml 2.6.1](https://github.com/onelogin/php-saml/releases/tag/v2.6.1)

**Comment by samlev** [comment]
Thanks :)

**Pull request merged**
