### PR TITLE
Change Fatal Error to Exception

### PR DESCRIPTION
**Pull request by stephanedelprat**
`OneLogin_Saml2_Utils::loadXML` returns `false` if input is not correct XML.

Which leads to a Fatal Error :

> Call to a member function getAttribute() on null in **/vendor/onelogin/php-saml/lib/Saml2/LogoutRequest.php:163

With this fix, an Exception is thrown instead.

### CODE REVIEW

**Comment by pitbulk** [comment]
Can you add a test user case for that.

Also, can you do the same for SAMLResponse [here](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/LogoutResponse.php#L64)?

**Comment by stephanedelprat** [comment]
I added the same Exception in SAMLResponse.

And the 2 unittests.

(this happened on the production server, so I don't know what they were sending instead of XML)

**Comment by pitbulk** [comment]
Great,

one last change. I saw that in [SAMLResponse](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L77) we show as error:
"SAML Response could not be processed"

can you replace the "XML is invalid" by
"LogoutRequest could not be processed" and "LogoutResponse could not be processed"

**Comment by stephanedelprat** [comment]
I changed the message.

Should I squash the commits ?

**Pull request merged**
