### PR TITLE
Use randomness from a CSPRNG to generate unique IDs for assertions

### PR DESCRIPTION
**Pull request by TimWolla**

### CODE REVIEW

**Comment by pitbulk** [comment]
Hi @TimWolla Do you know if this change could impact the performance of the uuid generation?

**Comment by TimWolla** [comment]
@pitbulk Yes, this change impacts performance ... my proposed new version is ~30% *FASTER* than the old one. Of course even if it would be slower, it would still be worth it for the increased security. `uniqid()` should really not be placed anywhere near something authentication/security.

```
$ cat bench.php 
<?php
function OLD_generateUniqueID() {
    return 'ONELOGIN_' . sha1(uniqid((string)mt_rand(), true));
}

function NEW_generateUniqueID() {
    return 'ONELOGIN_' . sha1(random_bytes(20));
}

$start = microtime(true);
for ($i = 0; $i < 1000000; ++$i) {
    OLD_generateUniqueID();
}
$end = microtime(true);
echo 'Old: '.($end - $start).PHP_EOL;

$start = microtime(true);
for ($i = 0; $i < 1000000; ++$i) {
    NEW_generateUniqueID();
}
$end = microtime(true);
echo 'New: '.($end - $start).PHP_EOL;
$ php --version
PHP 8.0.6 (cli) (built: May 12 2021 12:58:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.6, Copyright (c), by Zend Technologies
$ php bench.php 
Old: 1.0328059196472
New: 0.69966077804565
$ php bench.php 
Old: 1.0280342102051
New: 0.68713593482971
$ php bench.php 
Old: 1.0297458171844
New: 0.68583202362061
```

**Comment by pitbulk** [comment]
but take in mind that this is used to generate an uuid, nothing related with crypto.

Do you consider its use here insecure?

**Comment by TimWolla** [comment]
> Do you consider its use here insecure?

I'm not qualified to comment on this, as I am not a SAML expert. That's why I rely on a library doing the heavy lifting after all.

However: Simply using a CSPRNG removes any remaining doubt about whether it might or might not be insecure. It is no less secure than `uniqid()` and might be more secure. Consider this future-proofing in case the ID generator is used in a more critical location in a future change, if you will. It will also satisfy any static analysis tools flagging the use of `uniqid()`.

With the CSPRNG implementation even being 30% faster than the old implementation and this PR targetting the 4.x branch (which is PHP 7+), IMO we really should not need to have an extensive discussion about this?

**Pull request merged**
