### PR TITLE
Adding on/off settings for compression of SAML Requests and responses.

### PR DESCRIPTION
**Pull request by WillSkates**
@pitbulk This should fit more with your comments in #141.

Only change I made was to add a new 'compression' settings option instead of adding the options under 'security'. I also added a Onelogin_Saml2_Settings::checkCompressionSettings() method and tests for it.

Cheers,
Will

### CODE REVIEW

**Comment by pitbulk** [comment]
The code seems ok.

I saw that at the [python](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/authn_request.py#L133) toolkit we allow to get the request/response deflated or not by providing a parameter.

I will review ruby, python and your proposal and unify a solution.

**Comment by WillSkates** [comment]
@pitbulk You're right but I can't see that parameter actually being used e.g. : https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L291. It might be worth applying this solution for the python toolkit as well.

**Comment by pitbulk** [comment]
yes, I think I will do a mix, let users to enter "deflate" parameter to the get_request / get_response and the settings stuff (parameter will have priority)

**Comment by WillSkates** [comment]
@pitbulk would you like me to add the `$deflate` parameter here as well?

**Comment by pitbulk** [comment]
If you can gonna be welcome. But add it to the get_request get_response only, not to login/logout

**Comment by WillSkates** [comment]
@pitbulk That's in there now.

**Pull request merged**
