### PR TITLE
Change argument format of assert() method

### PR DESCRIPTION
**Pull request by webdevog**
Using string as the assertion is DEPRECATED as of PHP 7.2.
Read more http://php.net/manual/en/function.assert.php

### CODE REVIEW

**Comment by webdevog** [comment]
Hello!
I have issues with https://github.com/aacotroneo/laravel-saml2 which is not working with assertion arguments which are strings
According to http://php.net/manual/en/function.assert.php : 
"Using string as the assertion is DEPRECATED as of PHP 7.2."

Can you apply this fix, please?

**Comment by pitbulk** [comment]
There is a specific branch compatible with PHP7.2:
- [3.0.0-namespaceless](https://github.com/onelogin/php-saml/tree/3.0.0-namespaceless) (100% compatible with the current master branch).
- [3.0.0](https://github.com/onelogin/php-saml/tree/3.0.0) It uses namespaces, so you will need some changes in your code.

**Comment by sserbin** [comment]
Can we get this merged @pitbulk ? These changes are fully compatible with >= 5.3.2 (which is what in composer version constraint).

The branches suggested above are severely outdated btw.

**Comment by danielbeardsley** [comment]
I opened a new version of this pull request FYI at #377 

Though I didn't realize about version 3.0.0.

**Pull request closed without merging**
