### PR TITLE
Handles empty SignedInfo Reference for a referred full signed Response.

### PR DESCRIPTION
**Pull request by ricardofandrade**
When the SignedInfo Reference has a blank URI, we should NOT inject one if the full response is signed because that breaks the signature validation in some cases. In the other hand, by not doing that everything that expected the URI to not be empty will break because there's no URI to reference while extracting fields from the response. So we need to fallback on the response's actual ID.
For the case where the SignedInfo SHOULD have a URI pointing to the response but there's none, we just retry validating the signature with the injected URI, preserving the behavior with a reasonable performance penalty.

### CODE REVIEW

**Comment by pitbulk** [comment]
@ricardofandrade,
Please, review if the [no_uri branch](https://github.com/onelogin/php-saml/tree/no_uri) works for you.

**Comment by pitbulk** [comment]
Fixed https://github.com/onelogin/php-saml/commit/2b7cad84d17c6911a7000894abdd23e0ddb2e14a

**Comment by ricardofandrade** [comment]
My apologies, I didn't have the time to test it myself.
Thank you @pitbulk

**Comment by pitbulk** [comment]
@ricardofandrade 

Please test that master works for you now.

**Pull request closed without merging**
