### PR TITLE
Add attributes to attribute array using FriendlyName in getAttributes method

### PR DESCRIPTION
**Pull request by brjpeters**
I ran into an issue recently where the attribute Name was an OID and I was looking for the LDAP attribute name (`urn:oid:2.5.4.42` instead of `givenName`). For these type of attributes, sometimes there's a `FriendlyName` attribute on the attribute element.

The library doesn't currently use friendly names in any way that I could tell for attributes. This is an update to add the attribute values to the attributes array using the friendly name along side the name.

### CODE REVIEW

**Comment by brjpeters** [comment]
I didn't see #252 before this. This is hoping to accomplish the same thing but with a slightly DRYer approach.

**Comment by pitbulk** [comment]
Instead of modify the current getAttributes method, what do you think about adding a new getAttributesWithFriendlyName method that will return the friendly name version?

Please provide PR with tests and I will merge.

**Comment by brjpeters** [comment]
@pitbulk That sounds reasonable to me. I'll update this PR with that method and add tests.

**Comment by brjpeters** [comment]
@pitbulk Updated with the new method and a unit test.

**Comment by slaughter550** [comment]
@pitbulk instead of copying and pasting code with minor alterations, can't we just make `getAttributes()` accept a `attributeName` parameter that defaults to `Name` so no default behavior changes?

code signature would be 
```
public function getAttributes($keyName = 'Name')
```
```
$attributeName = $entry->attributes->getNamedItem($keyName)->nodeValue;
```

Which could then be called like `$this->getAttributes('FriendlyName')` if you wanted to key by a different key. I'd be happy to write the PR if needed

**Comment by pitbulk** [comment]
@slaughter550 is not bad idea. The problem I see is that there is a getAttribute method as well
getAttribute($name)
and maybe can be some confusion.

That why I prefer to. offer the getAttributesWithFriendlyName and getAttributeWithFriendlyName

**Comment by slaughter550** [comment]
@pitbulk If that is a concern to you, which I agree can be confusing to some, I would recommend abstracting it all a level and creating a `getAttributesByKeyName($keyName)` and then having `getAttributesByFriendlyName` and `getAttributes`, both of which just reuse that base function.

```
getAttributesByKeyName($keyName) {
...
    $attributeName = $entry->attributes->getNamedItem($keyName)->nodeValue;
...
}
```
and then
```
getAttributes() {
   return $this->getAttributesByKeyName('Name')
}
```
along with
```
getAttributesByFriendlyName() {
    return $this->getAttributesByKeyName('FriendlyName')
}
```

Because then they would both use the same code path and make the overall code much cleaner

**Comment by pitbulk** [comment]
@slaughter550 Agree, that should be the solution.

**Comment by pitbulk** [comment]
Need to push that on 3.0.0 too

**Comment by slaughter550** [comment]
@pitbulk to clean this PR up to what was suggested above. What branch do you want it against?

**Comment by pitbulk** [comment]
The feature is already merged on mastee

**Comment by slaughter550** [comment]
Right, but the method is copy pasted. Would you not want another PR to abstract this PR another level to what we talked about before?

**Comment by pitbulk** [comment]
What I added on master was refactored:
https://github.com/onelogin/php-saml/commit/7068f530b696feca8463fbc1bbe644ef52db2d73

**Comment by slaughter550** [comment]
Ohhhh sorry. Got it! Thanks!

**Comment by pitbulk** [comment]
There are a bunch of commits so yes, I will try to release a new version soon ;)

**Pull request merged**
