### PR TITLE
Support for attached signing certificates

### PR DESCRIPTION
**Pull request by Fredrik82**
Added support for using the public IdP signing certificate provided in the SAML response.

### CODE REVIEW

**Comment by pitbulk** [comment]
what the difference between x509cert and x509certRemote?

**Comment by Fredrik82** [comment]
The difference is that when you set x509certRemote to true, you don’t need to specify the public signing certificate in the config when using this toolkit. It will use the attached public certificate in the SAML response (if any).

Azure might renew the certificate at anytime. The single sign on will then be down until the config file is updated manually. This way we will prevent that downtime.

**Comment by pitbulk** [comment]
and what prevents then an attacker to sign a SAMLResponse with its own cert instead IdP cert?

**Comment by Fredrik82** [comment]
That is true. What if we verify that the certificate is issued by a trusted CA? Then the toolkit will then support "anchored" trust, like "I trust the issuer of the certificate".

**Comment by pitbulk** [comment]
Why not better follow the SAML standard and verify that the cert matches the one registered previously on the SP settings and keep that value sync?

**Comment by Fredrik82** [comment]
As I explained earlier: "Azure might renew the certificate at anytime. The single sign on will then be down until the config file is updated manually. This way we will prevent that downtime."

My aim is to automate this. Even if I have a separate script that polls the public Federation xml I'll still be exposed to the fact that an attacker might pretend to be the IdP.

**Comment by pitbulk** [comment]
"Even if I have a separate script that polls the public Federation xml I'll still be exposed to the fact that an attacker might pretend to be the IdP."

No, since SP only trust on the IdP and its cert, that is related with the private key used to sign the SAMLResponse.

If you create an script that read the IdP and its cert for a valid URL under https and you access it validating the cert of the https, you reduce the risk more than trusting a SAMLResponse alone with no context.

**Pull request closed without merging**
