### PR TITLE
PHP 8 test suite

### PR DESCRIPTION
**Pull request by fideloper**
This depends on PR https://github.com/onelogin/php-saml/pull/458, which should be pulled in first.

This does a few things:

1. Makes the min PHP version 7.1
2. Updates phpunit for php8 (while allowing a phpunit version for php 7.1+)
3. Cleans up errors related to phpunit depreciations/changes

We still get 2 errors in phpunit to deal with:

1. Errors `Test was run in child process and ended unexpectedly`
2. This last error, which I'm not sure about:

```
22) OneLogin\Saml2\Tests\ResponseTest::testIsInValidCert
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'openssl_x509_read(): supplied parameter cannot be coerced into an X509 certificate!'
+'openssl_x509_read(): X.509 Certificate cannot be retrieved'
```

### CODE REVIEW

**Comment by pitbulk** [comment]
Not sure if we can deprecate PHP 5.X on the 3.X branch, many projects depend on it.

**Comment by fideloper** [comment]
Right - this is a bit awkward as we're being pushed in that direction due to phpunit and its PHP version constraints. We end up in a weird spot in terms of phpunit version needed to test on php 8.

**Comment by pitbulk** [comment]
@fideloper I merged this on php4.0.0 brach.

it seems that the assertMatchesRegularExpression method is available on phpunit 9.5 which requires PHP 7.3
Can we use other similar method in order to make the toolkit compatible with PHP7.1 as was our initial goal or may we simply for to PHP7.3?

**Comment by fideloper** [comment]
Hmmmm - my first thought is to make the minimum php7.3, since we're doing a new major version (version 4) and only php7.3+ is currently supported (https://www.php.net/supported-versions.php).

That'd be my personal preference, but I don't have as good an understanding on the demands of the project and PHP support needs. I'm open to doing a similar version check to decide which methods to use/call in the test suite!

**Comment by pitbulk** [comment]
Ok, let's force PHP 7.3 then

**Pull request merged**
