### PR TITLE
fix(composer): Exclude test files from Composer production downloads

### PR DESCRIPTION
**Pull request by klausi**
Test code should not end up in a production deployment for security reasons. Please exclude test code from Composer downloads. This can be done with https://blog.madewithlove.be/post/gitattributes/

Not sure if you also want to exclude other stuff like README and example files?

### CODE REVIEW

**Comment by pitbulk** [comment]
Maybe makes sense to allow on composer production only:
- docs
- lib/Saml2
- extlib
- certs
- settings_example.php
- advanced_settings_example.php
- CHANGELOG
- LICENSE
- README.md  

and ignore the rest

**Comment by klausi** [comment]
I think with .gitattributes you have to specify a black list (stuff that you want to ignore). Composer is primitive when it looks at those lines, so I think a white list is not possible https://github.com/composer/composer/blob/master/src/Composer/Package/Archiver/GitExcludeFilter.php

**Comment by klausi** [comment]
What about the endpoint folder? I left that in. Same for the other *.php files in the root folder, people might want to use them for whatever reasons.

Otherwise I removed the demo* folders.

**Comment by pitbulk** [comment]
we may exclude endpoints as well and the rest of php files not listed in the previous list I shared ;)

**Pull request merged**
